/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'main-colour': '#',
        'nav-colour': '#',
        'footer-colour': '#',
        'colour-pale': '#',
        'colour-light': '#',
        'colour-med': '#',
        'colour-dark': '#',
        'transparent-black': 'rgba(0, 0, 0, 0.65)',
        'transparent-black-2': 'rgba(0, 0, 0, 0.85)',
        'transparent-white': 'rgba(255, 255, 255, 0.65)',
        'transparent-white-2': 'rgba(255, 255, 255, 0.45)',
        'transparent-purple': 'rgba(147, 51, 234, 0.65)',
        'transparent-green': 'rgba(22, 163, 74, 0.65)',
        'transparent-yellow': 'rgba(234, 179, 8, 0.65)',
        'main-text': '#000000',
        'alt-text': '#ffffff',
        'hover-text': '#',
        'active-text': '#',
        'placeholder-text': 'rgb(55 65 81)',
        'error-red': '',
        'success-green': '',
        'event-red': '',
        'hyperlink-blue': '#2563eb',
        secleted: '#2563eb',
        'non-selected': '#cbd5e1',
      },
    },
  },
  plugins: [],
};
